/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SupplyChain {
  export type TransferRecordStruct = {
    from: AddressLike;
    to: AddressLike;
    timestamp: BigNumberish;
    status: BigNumberish;
    location: string;
    transactionHash: BytesLike;
  };

  export type TransferRecordStructOutput = [
    from: string,
    to: string,
    timestamp: bigint,
    status: bigint,
    location: string,
    transactionHash: string
  ] & {
    from: string;
    to: string;
    timestamp: bigint;
    status: bigint;
    location: string;
    transactionHash: string;
  };
}

export interface SupplyChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allProductIds"
      | "confirmDelivery"
      | "getAllProductIds"
      | "getProduct"
      | "getProductHistory"
      | "getProductHistoryLength"
      | "getTotalProducts"
      | "getUser"
      | "getUserProducts"
      | "owner"
      | "productCount"
      | "productHistory"
      | "products"
      | "registerProduct"
      | "registerUser"
      | "transferProduct"
      | "transferProductWithPayment"
      | "userProducts"
      | "users"
      | "verifyProduct"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PaymentTransferred"
      | "ProductRegistered"
      | "ProductStatusUpdated"
      | "ProductTransferred"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allProductIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmDelivery",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProductIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProduct",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProductHistory",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProductHistoryLength",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalProducts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserProducts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "productCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "productHistory",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "products", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "registerProduct",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferProduct",
    values: [BytesLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferProductWithPayment",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "userProducts",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "users", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "verifyProduct",
    values: [BytesLike, string, string, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allProductIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProductIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProduct", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProductHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProductHistoryLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalProducts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserProducts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "productCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "productHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "products", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferProductWithPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userProducts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyProduct",
    data: BytesLike
  ): Result;
}

export namespace PaymentTransferredEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    productId: BytesLike
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    productId: string
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    productId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductRegisteredEvent {
  export type InputTuple = [
    productId: BytesLike,
    name: string,
    producer: AddressLike,
    price: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: string,
    name: string,
    producer: string,
    price: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: string;
    name: string;
    producer: string;
    price: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductStatusUpdatedEvent {
  export type InputTuple = [
    productId: BytesLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    productId: string,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    productId: string;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductTransferredEvent {
  export type InputTuple = [
    productId: BytesLike,
    from: AddressLike,
    to: AddressLike,
    status: BigNumberish,
    location: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: string,
    from: string,
    to: string,
    status: bigint,
    location: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: string;
    from: string;
    to: string;
    status: bigint;
    location: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [
    userAddress: AddressLike,
    role: BigNumberish,
    name: string
  ];
  export type OutputTuple = [userAddress: string, role: bigint, name: string];
  export interface OutputObject {
    userAddress: string;
    role: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SupplyChain extends BaseContract {
  connect(runner?: ContractRunner | null): SupplyChain;
  waitForDeployment(): Promise<this>;

  interface: SupplyChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allProductIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  confirmDelivery: TypedContractMethod<
    [_productId: BytesLike, _location: string],
    [void],
    "nonpayable"
  >;

  getAllProductIds: TypedContractMethod<[], [string[]], "view">;

  getProduct: TypedContractMethod<
    [_productId: BytesLike],
    [
      [string, string, string, string, string, bigint, bigint, bigint] & {
        productHash: string;
        name: string;
        description: string;
        producer: string;
        currentOwner: string;
        price: bigint;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getProductHistory: TypedContractMethod<
    [_productId: BytesLike],
    [SupplyChain.TransferRecordStructOutput[]],
    "view"
  >;

  getProductHistoryLength: TypedContractMethod<
    [_productId: BytesLike],
    [bigint],
    "view"
  >;

  getTotalProducts: TypedContractMethod<[], [bigint], "view">;

  getUser: TypedContractMethod<
    [_userAddress: AddressLike],
    [[bigint, string, boolean]],
    "view"
  >;

  getUserProducts: TypedContractMethod<
    [_userAddress: AddressLike],
    [string[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  productCount: TypedContractMethod<[], [bigint], "view">;

  productHistory: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, string, string] & {
        from: string;
        to: string;
        timestamp: bigint;
        status: bigint;
        location: string;
        transactionHash: string;
      }
    ],
    "view"
  >;

  products: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        productHash: string;
        name: string;
        description: string;
        producer: string;
        currentOwner: string;
        price: bigint;
        createdAt: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  registerProduct: TypedContractMethod<
    [
      _name: string,
      _description: string,
      _price: BigNumberish,
      _location: string
    ],
    [string],
    "nonpayable"
  >;

  registerUser: TypedContractMethod<
    [_role: BigNumberish, _name: string],
    [void],
    "nonpayable"
  >;

  transferProduct: TypedContractMethod<
    [_productId: BytesLike, _to: AddressLike, _location: string],
    [void],
    "nonpayable"
  >;

  transferProductWithPayment: TypedContractMethod<
    [_productId: BytesLike, _location: string],
    [void],
    "payable"
  >;

  userProducts: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  users: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, string, boolean] & {
        role: bigint;
        name: string;
        isRegistered: boolean;
      }
    ],
    "view"
  >;

  verifyProduct: TypedContractMethod<
    [
      _productId: BytesLike,
      _name: string,
      _description: string,
      _price: BigNumberish,
      _producer: AddressLike
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allProductIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "confirmDelivery"
  ): TypedContractMethod<
    [_productId: BytesLike, _location: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllProductIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getProduct"
  ): TypedContractMethod<
    [_productId: BytesLike],
    [
      [string, string, string, string, string, bigint, bigint, bigint] & {
        productHash: string;
        name: string;
        description: string;
        producer: string;
        currentOwner: string;
        price: bigint;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProductHistory"
  ): TypedContractMethod<
    [_productId: BytesLike],
    [SupplyChain.TransferRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProductHistoryLength"
  ): TypedContractMethod<[_productId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalProducts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<
    [_userAddress: AddressLike],
    [[bigint, string, boolean]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserProducts"
  ): TypedContractMethod<[_userAddress: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "productCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "productHistory"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, string, string] & {
        from: string;
        to: string;
        timestamp: bigint;
        status: bigint;
        location: string;
        transactionHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "products"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        productHash: string;
        name: string;
        description: string;
        producer: string;
        currentOwner: string;
        price: bigint;
        createdAt: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProduct"
  ): TypedContractMethod<
    [
      _name: string,
      _description: string,
      _price: BigNumberish,
      _location: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<
    [_role: BigNumberish, _name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferProduct"
  ): TypedContractMethod<
    [_productId: BytesLike, _to: AddressLike, _location: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferProductWithPayment"
  ): TypedContractMethod<
    [_productId: BytesLike, _location: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "userProducts"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, string, boolean] & {
        role: bigint;
        name: string;
        isRegistered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyProduct"
  ): TypedContractMethod<
    [
      _productId: BytesLike,
      _name: string,
      _description: string,
      _price: BigNumberish,
      _producer: AddressLike
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "PaymentTransferred"
  ): TypedContractEvent<
    PaymentTransferredEvent.InputTuple,
    PaymentTransferredEvent.OutputTuple,
    PaymentTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProductRegistered"
  ): TypedContractEvent<
    ProductRegisteredEvent.InputTuple,
    ProductRegisteredEvent.OutputTuple,
    ProductRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProductStatusUpdated"
  ): TypedContractEvent<
    ProductStatusUpdatedEvent.InputTuple,
    ProductStatusUpdatedEvent.OutputTuple,
    ProductStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProductTransferred"
  ): TypedContractEvent<
    ProductTransferredEvent.InputTuple,
    ProductTransferredEvent.OutputTuple,
    ProductTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "PaymentTransferred(address,address,uint256,bytes32)": TypedContractEvent<
      PaymentTransferredEvent.InputTuple,
      PaymentTransferredEvent.OutputTuple,
      PaymentTransferredEvent.OutputObject
    >;
    PaymentTransferred: TypedContractEvent<
      PaymentTransferredEvent.InputTuple,
      PaymentTransferredEvent.OutputTuple,
      PaymentTransferredEvent.OutputObject
    >;

    "ProductRegistered(bytes32,string,address,uint256,uint256)": TypedContractEvent<
      ProductRegisteredEvent.InputTuple,
      ProductRegisteredEvent.OutputTuple,
      ProductRegisteredEvent.OutputObject
    >;
    ProductRegistered: TypedContractEvent<
      ProductRegisteredEvent.InputTuple,
      ProductRegisteredEvent.OutputTuple,
      ProductRegisteredEvent.OutputObject
    >;

    "ProductStatusUpdated(bytes32,uint8,uint8)": TypedContractEvent<
      ProductStatusUpdatedEvent.InputTuple,
      ProductStatusUpdatedEvent.OutputTuple,
      ProductStatusUpdatedEvent.OutputObject
    >;
    ProductStatusUpdated: TypedContractEvent<
      ProductStatusUpdatedEvent.InputTuple,
      ProductStatusUpdatedEvent.OutputTuple,
      ProductStatusUpdatedEvent.OutputObject
    >;

    "ProductTransferred(bytes32,address,address,uint8,string,uint256)": TypedContractEvent<
      ProductTransferredEvent.InputTuple,
      ProductTransferredEvent.OutputTuple,
      ProductTransferredEvent.OutputObject
    >;
    ProductTransferred: TypedContractEvent<
      ProductTransferredEvent.InputTuple,
      ProductTransferredEvent.OutputTuple,
      ProductTransferredEvent.OutputObject
    >;

    "UserRegistered(address,uint8,string)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
